version: '3'
services:
  server:
    container_name: postgres1
    restart: always
    build: .
    ports: 
      - '8888:8888'
    environment:
      DATABASE_URL: postgres://postgres:lifeiscool@postgres:5432/postgres
    depends_on: 
      - "postgres"
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:11.1
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: lifeiscool
      
